### ISSUE TITLE
**EPIC Service Definition (SLI, SLO, and SLAs)**Background Reading: `https://service-docs.docs.shopify.io/service_level_objectives/service_level_objectives.html

### ISSUE THREAD

**Issue by chopchop505** [chopchop505/surfana#16]
- [ ] Explain your reasoning for your SLO definition?  Why did you decided on X?
- [ ] How do you calculate your SLOs? Feel free to point to exact endpoints in code, datadog?
- [ ] Where are you SLOs monitored?
- [ ] Are you alerting on SLO?
- [ ] Are your SLOs visible in ServicesDB
