### ISSUE TITLE
[EPIC] Service Definition

### ISSUE THREAD

**Issue by chopchop505** [chopchop505/surfana#17]
()

[Maturity Levels]()
1. SLOs defined
2. SLS defined, but they are inaccurate
....

[Resources]**Exit Criteria**
- [ ] Explain your reasoning for your SLO definition?  Why did you decided on X?
- [ ] How do you calculate your SLOs?
- [ ] Where are you SLOs monitored?
- [ ] Are your SLOs visible in ServicesDB?
- [ ] Do you have error budget policies?
- [ ] How do you monitor error budget polices?
